# -*- coding: utf-8 -*-
"""school data  management .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rfvji-yM2mdFWgSInqEcpFilNpPl60ZW
"""

# School Data Management System (Beginner Level)

students = {}   # Dictionary for storing student data

while True:

    print("\n===== SCHOOL MENU =====")
    print("1. Add Student")
    print("2. Display All Students")
    print("3. Search Student")
    print("4. Remove Student")
    print("5. Show Class Topper")
    print("6. Show Unique Sections")
    print("7. Exit")

    choice = input("Enter your choice: ")

    #  ADD STUDENT
    if choice == "1":
        try:
            roll = int(input("Enter Roll Number of the Student: "))

            if roll in students:
                print("Roll number already exists!")
            else:
                name = input("Enter Name: ")
                age = int(input("Enter Age: "))

                print("Enter marks of 3 subjects:")
                s1 = int(input("PYTHON: "))
                s2 = int(input("DBMS: "))
                s3 = int(input("FLAT: "))

                marks = (s1, s2, s3)   # Tuple

                section = input("Enter Section: ")

                total = s1 + s2 + s3
                average = total / 3


                if average >= 85:
                    grade = "A+"
                elif average >= 80:
                    grade = "A"
                elif average >= 70:
                    grade = "B"
                elif average >= 60:
                    grade ="C"
                elif average >= 50:
                    grade ="Pass"
                else:
                    grade = "Fail"

                students[roll] = {
                    "Name": name,
                    "Age": age,
                    "Marks": marks,
                    "Total": total,
                    "Average": average,
                    "Grade": grade,
                    "Section": section
                }

                print("Student added successfully!")

        except:
            print("Invalid input!")

    #  DISPLAY
    elif choice == "2":
        if len(students) == 0:
            print("No students found.")
        else:
            for roll in students:
                print("\nRoll:", roll)
                for key in students[roll]:
                    print(key, ":", students[roll][key])

    #SEARCH
    elif choice == "3":
        try:
            roll = int(input("Enter Roll Number to search: "))
            if roll in students:
                print(students[roll])
            else:
                print("Student not found!")
        except:
            print("Invalid input!")

    #  REMOVE
    elif choice == "4":
        try:
            roll = int(input("Enter Roll Number to remove: "))
            if roll in students:
                del students[roll]
                print("Student removed successfully!")
            else:
                print("Student not found!")
        except:
            print("Invalid input!")

    #  TOPPER
    elif choice == "5":
        if len(students) == 0:
            print("No students available.")
        else:
            highest = 0
            topper_roll = 0

            for roll in students:
                if students[roll]["Total"] > highest:
                    highest = students[roll]["Total"]
                    topper_roll = roll

            print("Class Topper Roll Number:", topper_roll)
            print("Details:", students[topper_roll])

    # UNIQUE SECTIONS
    elif choice == "6":
        sections = set()   # Set

        for roll in students:
            sections.add(students[roll]["Section"])

        print("Unique Sections:", sections)

    #  EXIT
    elif choice == "7":
        print("Program Ended")
        break

    else:
        print("Invalid choice! Try again.")